### ISSUE TITLE
`develop` builds broken again! 

### ISSUE THREAD

**Issue by mblomdahl** [libris/definitions#7]
After merging pull request #6 on 7th September, `python datasets.py` was working from a clean checkout. Since then around 15 commits have been added and it doesn't work building any longer.

How to reproduce:
```bash
mkdir test && cd test/
git clone https://github.com/libris/definitions.git -b develop
cd definitions/ && virtualenv venv && . venv/bin/activate && pip install -r requirements.txt
python datasets.py > output.log  # Bang!
```

```python
Traceback (most recent call last):
  File "datasets.py", line 296, in <module>
    compiler.main()
  File "/Users/mblomdahl/PyCharm/definitions/test/definitions/venv/src/lxltools/lxltools/datacompiler.py", line 58, in main
    self._run(args.datasets)
  File "/Users/mblomdahl/PyCharm/definitions/test/definitions/venv/src/lxltools/lxltools/datacompiler.py", line 74, in _run
    self._compile_datasets(names)
  File "/Users/mblomdahl/PyCharm/definitions/test/definitions/venv/src/lxltools/lxltools/datacompiler.py", line 99, in _compile_datasets
    result = build()
  File "datasets.py", line 207, in languages
    'iso6391.ttl').query(cherry_pick_loc_lang_data)
  File "datasets.py", line 38, in _get_zipped_graph
    return Graph().parse(zipped.open(name), format='turtle')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 964, in open
    zinfo = self.getinfo(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 912, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'iso6391.ttl' in the archive"
```

@klngwll @sarwik I've been scanning through your changes, but I'm totally clueless.. Any thoughts on which of them could have caused this?

**Comment by mblomdahl** [comment]
@mxtthias I think it would be nice adding a Jenkinsfile to definitions repo, so we get notified instantly when things break. Very time consuming to check out the commits one by one to backtrack where the error occurs. What do you think about it?

**Comment by mblomdahl** [comment]
@sarwik Me and @klngwll was looking at this a little.. It seems the issue is stems from a format change from id.loc.gov provider.

This is what the old zip file used to look like (containing a single `iso6391.ttl` file):
[http%3A%2F%2Fid.loc.gov%2Fstatic%2Fdata%2Fvocabularyiso639-1.ttl.zip](https://github.com/libris/definitions/files/1295625/http.3A.2F.2Fid.loc.gov.2Fstatic.2Fdata.2Fvocabularyiso639-1.ttl.zip)

When downloading a new vocabularyiso639-1.ttl.zip, it does not contain `iso6391.ttl` but instead a `vocabularyiso639-1.ttl` with different contents. If you want to try it out locally:
```bash
wget http://id.loc.gov/static/data/vocabularyiso639-1.ttl.zip
unzip vocabularyiso639-1.ttl.zip
```

**Comment by mxtthias** [comment]
Closed by https://github.com/libris/definitions/commit/7825de4cec6138fb1d92c9f98fdf135f667f91bb
